/*
 * generated by Xtext 2.31.0
 */
package eu.fbk.se.simpledg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SimpleDGUiModule extends AbstractSimpleDGUiModule {

	public SimpleDGUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
