/*
 * generated by Xtext 2.31.0
 */
package eu.fbk.se.simpledg.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import eu.fbk.se.simpledg.simpleDG.DirectedGraph

@ExtendWith(InjectionExtension)
@InjectWith(SimpleDGInjectorProvider)
class SimpleDGParsingTest {
	@Inject
	ParseHelper<DirectedGraph> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Nodes:
				^A 
				^B
				^C	
			;
			Edges:
				^B -> ^A	
				^A -> ^C
			;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
