/*
 * generated by Xtext 2.31.0
 */
package eu.fbk.se.simpledg;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SimpleDGStandaloneSetup extends SimpleDGStandaloneSetupGenerated {

	public static void doSetup() {
		new SimpleDGStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
