/*
 * generated by Xtext 2.31.0
 */
package eu.fbk.se.simpledg;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimpleDGRuntimeModule extends AbstractSimpleDGRuntimeModule {
}
