/*
 * generated by Xtext 2.31.0
 */
package eu.fbk.se.simpledg.validation;

import org.eclipse.xtext.validation.Check;

import eu.fbk.se.simpledg.simpleDG.DotGraphs;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SimpleDGValidator extends AbstractSimpleDGValidator {
	
	public static final String UNDEFINED_NODE = "Node is not defined: ";

	/**
	 * Check if all the nodes used in the EdgesDefinition are defined in NodesDefinition
	 * @param dg A DotGraphs object
	 */
	@Check
	public void checkAllNodesDefined(DotGraphs dg) {
			
		
	
	}
	
	
	/**
	 * Check if the node names are unique. 
	 * Duplicated node names are not allowed and the validator has to return an error.
	 * @param dg A DotGraphs object
	 */
	@Check
	public void checkDuplicatedNodes(DotGraphs dg) {
		
	}
	
	
	/**
	 * Check if there are duplicated edges. 
	 * Duplicated edges are not allowed and the validator has to return an error.
	 * @param dg A DotGraphs object
	 */
	@Check
	public void checkDuplicatedEdges(DotGraphs dg) {
		
	}
	
	
	
	
}
